### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MendeBadra** [JuliaNeuralGraphics/GaussianSplatting.jl#28]
I had downloaded a colmap dataset and tried to use it in `gui` function. But it seems to be working but the CUDA is always says out of memory. I have tested on 2 separate gpus gtx1650 and rtx 3080ti.

**Comment by pxl-th** [comment]
What is the resolution of images in your dataset?
You may need to pass `scale` parameter that is multiple of `2` to fit into your GPU (which will use downscaled versions of images).

E.g.:
```
julia> GaussianSplatting.gui("<path-to-dataset>"; scale=4)
```

**Comment by MendeBadra** [comment]
resolutions were 4000 by 3000.

**Comment by pxl-th** [comment]
Try version 1.0.1 (just tagged a new release) or main branch (`]add https://github.com/JuliaNeuralGraphics/GaussianSplatting.jl.git`), the issue was fixed some time ago.

**Comment by MendeBadra** [comment]
Ah the steps and Loss are changing tho.

**Comment by pxl-th** [comment]
Glad to hear it! I get good performance on RTX3060 with ~1080p resolution images and disabling training when moving camera around.
